### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by HeyProtagonist** [gopinav/React-Tutorials#5]
Hi received this error with while `npm start`
refer attached text file for full log.
[npm_start_error.txt](https://github.com/gopinav/React-Tutorials/files/5824063/npm_start_error.txt)

**Comment by HeyProtagonist** [comment]
++ Resolved issue deleting `npm cache` in `user/roaming`.

There should me some problems with name previously created and the npm assigned the another port without removing it.

Thanks for the great detailed tuts.

**Comment by sai58-56** [comment]
/src/index.js
Module not found: Can't resolve './serviceWorker' in 'C:\Users\kakar\form-1\src'
This error occurred during the build time and cannot be dismissed.
same error coming for form

**Comment by HeyProtagonist** [comment]
> /src/index.js
> Module not found: Can't resolve './serviceWorker' in 'C:\Users\kakar\form-1\src'
> This error occurred during the build time and cannot be dismissed.
> same error coming for form

**can you provide a clear explanation of the issue you're facing?**
